### ISSUE TITLE
Include json support

### ISSUE THREAD

**Issue by clsource** [avivbeeri/dome#57]
Including support for json files may be handy for reading files created using this format.

Example of a use case.

https://lottiefiles.com/

With that lib you could create animation based on json files. (A parser would have to be implemented though) but the minimum requirement is having json support.

Heres a simple json c implementation
https://github.com/sheredom/json.h

👍

**Comment by avivbeeri** [comment]
I'm not sure I want to include an entire JSON parser in DOME, but I appreciate the need for some structured way to include configuration data. One option is to use a module like this in your project: https://github.com/brandly/wren-json

I'd have to do some research into how the parsing API works, because my past attempts at using JSON, TOML and similar config languages have ended up being highly unperformant.

Wren has some decent String handling utilites for splitting and joining text, which I use for custom config formats at the moment.

**Comment by clsource** [comment]
Thanks. I did not knew that wren-json lib. May be enough to most projects have that json parser. Optionally could be included as a utils or helpers package. 👍
