### ISSUE TITLE
Default audio buffer length may be too small for some machines

### ISSUE THREAD

**Issue by scholar-mage** [avivbeeri/dome#9]
The default audio buffer length of 4096 appears to be too low for my machine, which causes choppy audio. Increasing it to 8192 in src/engine/audio.c appears to alleviate the issue for me.

**Comment by avivbeeri** [comment]
I had increased this to 8192 in [7b9e102](https://github.com/avivbeeri/dome/commit/7b9e1024eecdef0f5526641921957093eba1264e), but it causes some noticeable latency, which may have caused #10 , so I've reduced it to 4096 again.

Because the audio mixer now runs in a separate thread (see #18), I'm hoping the choppy audio issue is gone, but cross-platform testing will be needed.

**Comment by avivbeeri** [comment]
I've reduced this down to 2048 by default, but you can also tune it as a command line parameter by doing `./dome --buffer=n` if you find it needs to be resized.

Because the sample buffer has to be a power of 2, `n` is the power of 2, so to use a size of 2048 (2^11), `n = 11`.
